### PR TITLE
Added analytics

### PR DESCRIPTION
**Pull request by maxxcrawford**
Added analytics script to footer created analytics file from Google Analytics.

I confirmed that the file is serving correctly on local.

### CODE REVIEW

**Comment by maxxcrawford** [comment]
@gregtatum @groovecoder If there's a specific Tulsa Web Devs Gmail account, we can set up analytics that way, rather than using my personal account and sharing access.

**Comment by jsatt** [comment]
@maxxcrawford, we do have a TWD analytics account and even a 200OK property. Looks like it just didn't get added when we overhauled the site last year. Tracking id: UA-20201601-6

**Comment by maxxcrawford** [comment]
@jsatt Updated to the proper ID, and confirmed working on my local env.

**Comment by gregtatum** [comment]
@jsatt I don't think we ever added it. Can I get access to the analytics?

**Comment by jsatt** [comment]
@gregtatum, I have view access, but not add users. @groovecoder will have to get you access, it's attached to his Google account.

**Comment by groovecoder** [comment]
Hmm ... I have a "200ok Developer Conference" account in GA, but it has no data, and I don't have permissions to add users to it. Do I have the wrong one?

**Comment by jsatt** [comment]
@groovecoder, no I think it's a different one. There's a tulsawebdev.org
account (number 20201601), with properties for 200OK, tulsawebdevs.org,
oklahomadata.org tulsahackathon.com, etc.[image: Inline image 1]

**Pull request merged**
