### PR TITLE
Added Archive

### LINKED ISSUE #292: Add link to 2016 site
Link already exists, just need to put it on the main site
https://200ok.us/archive-2016/

### PR DESCRIPTION
**Pull request by hkbertoson**
I am not sure if this is what you were wanting. But I just added a new page called Archive and put the 2016 underneath that. This to resolve #292

### CODE REVIEW

**Comment by kacollins** [comment]
Would you also please add a line at the very bottom of the main site like on https://thunderplainsconf.com/ where it has `Previous Years: 2022`

**Review by kacollins — CHANGES_REQUESTED** [review]
Would you also please add a line at the very bottom of the main site like on https://thunderplainsconf.com/ where it has `Previous Years: 2022`

**Comment by hkbertoson** [comment]
Sure! Just a few

**Review by travismiller — CHANGES_REQUESTED** [review]
@hkbertoson thanks for contributing!

I think if you don't include the `package-lock.json` change in your commit, the preview deploy will pass. There are probably some other changes that need to be included to change Node version and/or change dependencies. We would want to do that in a separate PR.

Thanks again!

**Review by kacollins — APPROVED** [review]

**Review by kacollins — CHANGES_REQUESTED** [review]
I'm not seeing the previous years in the footer. What we're looking to build up is something like this at the bottom of the main page: 
image

**Comment by hkbertoson** [comment]
I swear I addd them. Not sure what happened... Getting it fixed.

**Review by hkbertoson — COMMENTED** [review]
Got it updated!

**Comment by kacollins** [comment]
This closes #292, #291, #290, #289, and #288

**Review by kacollins — APPROVED** [review]

**Comment by maxxcrawford** [comment]
@travismiller I know we've made changes for the 2023 site. Can we get this merged in?

**Comment by kacollins** [comment]
Might just have to close this PR and get the Oklathon folks to add this to the footer in the current version of the site

**Comment by maxxcrawford** [comment]
@kacollins Let's do that. I have a follow-up PR for the other site updates, and have left some commented code for where to put this.

**Comment by maxxcrawford** [comment]
See #306 (This file in [particular](https://github.com/techlahoma/200ok-site/pull/306/files#diff-4ea32a69a9e28d93e3f15457aa7511adbfa0c11474d5a5ad871e9930d64b1430R21-R28)) for where to add the new links for 2024

**Pull request closed without merging**
